-- ALTER : 객체 수정 구문

-- 컬럼 추가, 삭제, 수정
SELECT * FROM DEPT_COPY;

-- 컬럼 추가
ALTER TABLE DEPT_COPY
ADD (CNAME VARCHAR2(20));

-- 컬럼 추가 시 DEFAULT 값 지정
ALTER TABLE DEPT_COPY
ADD (LNAME VARCHAR2(40) DEFAULT '한국');

-- 컬럼 수정
DESC DEPT_COPY;

ALTER TABLE DEPT_COPY
MODIFY DEPT_ID CHAR(3)
MODIFY DEPT_TITLE VARCHAR2(30)
MODIFY LOCATION_ID VARCHAR2(2)
MODIFY CNAME CHAR(20)
MODIFY LNAME DEFAULT '미국';  -- 이미 들어가 있는 기본값 말고 새로 넣는 데이터의 기본 값 지정

SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
MODIFY DEPT_TITLE VARCHAR2(10);
-- cannot decrease column length because some value is too big  안에 들어있는 데이터 크기가 10이 넘는게 있어서 줄일 수 없음 에러 뜸


-- 컬럼 삭제 : 데이터가 기록되어 있어도 삭제 가능
--            삭제한 컬럼은 복구 불가
--            테이블에는 최소 한 개의 컬럼이 존재해야 함 : 모든 컬럼 삭제 불가
CREATE TABLE DEPT_COPY2
AS SELECT * FROM DEPT_COPY;

SELECT * FROM DEPT_COPY2;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN LOCATION_ID;

ALTER TABLE DEPT_COPY2
DROP COLUMN CNAME;

ALTER TABLE DEPT_COPY2
DROP COLUMN DEPT_TITLE;

ALTER TABLE DEPT_COPY2
DROP COLUMN LNAME;

SELECT * FROM DEPT_COPY2;

ROLLBACK;

-- 제약조건이 설정되어 있는 컬럼 삭제
CREATE TABLE TB1(
    PK1 NUMBER PRIMARY KEY,
    COL1 NUMBER,
    CHECK(PK1 > 0 AND COL1 > 0)
);

CREATE TABLE TB2(
    PK2 NUMBER PRIMARY KEY,
    FK2 NUMBER REFERENCES TB1,
    COL2 NUMBER,
    CHECK(PK2 > 0 AND COL2 > 0)
);

ALTER TABLE TB2
DROP COLUMN FK2;

ALTER TABLE TB1
DROP COLUMN PK1;    -- "column is referenced in a multi-column constraint"

ALTER TABLE TB2
DROP COLUMN PK2;    -- "column is referenced in a multi-column constraint"

SELECT * FROM TB2;

ALTER TABLE TB1
DROP COLUMN PK1 CASCADE CONSTRAINTS;

ALTER TABLE TB2
DROP COLUMN PK2 CASCADE CONSTRAINTS;

-- 제약 조건 추가, 삭제
ALTER TABLE DEPT_COPY
DROP CONSTRAINT SYS_C007028;
--MODIFY SYS_C007028 NULL;

-- 컬럼, 제약조건, 테이블 이름 변경
-- 컬럼 이름 변경
SELECT * FROM DEPT_COPY;

ALTER TABLE DEPT_COPY
RENAME COLUMN DEPT_TITLE TO DEPT_NAME;

SELECT * FROM DEPT_COPY;

-- 제약 조건 이름 변경
ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT SYS_C007041 TO UF_UP_NN;

ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT SYS_C007042 TO UF_UN_PK;

ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT SYS_C007043 TO UF_UN_UQ;

ALTER TABLE USER_FOREIGNKEY
RENAME CONSTRAINT FK_GRADE_CODE TO UF_UN_FK;

-- 테이블 명 변경
ALTER TABLE DEPT_COPY
RENAME TO DEPT_TEST;

ROLLBACK;
-- 테이블 삭제
DROP TABLE DEPT_TEST
CASCADE CONSTRAINTS;

